// Generated by scripts/generateCapabilityContract.cjs from server/utils/permissions.js.
// Navigation uses this mirror; server policies authorize every operation.

export const ROLE_LABELS: Record<string, string> = {
  "super_admin": "Super Admin",
  "admin": "Admin",
  "operations_admin": "Staff Operations Admin",
  "pm": "PM / Project Manager",
  "petition_writer": "Petition Writer",
  "business_plan_specialist": "Business Plan Specialist",
  "recommendation_letter_specialist": "Recommendation Letter Specialist",
  "uscis_forms_specialist": "USCIS Forms Specialist",
  "evidence_collector": "Evidence Collector",
  "reviewer": "Reviewer / QA",
  "editor": "Editor",
  "viewer": "Viewer"
};

export const ALL_ROLES: string[] = [
  "super_admin",
  "admin",
  "operations_admin",
  "pm",
  "petition_writer",
  "business_plan_specialist",
  "recommendation_letter_specialist",
  "uscis_forms_specialist",
  "evidence_collector",
  "reviewer",
  "editor",
  "viewer"
];

export const MANAGER_ROLES: string[] = [
  "super_admin",
  "admin",
  "operations_admin",
  "pm"
];

export const SPECIALIST_ROLES: string[] = [
  "petition_writer",
  "business_plan_specialist",
  "recommendation_letter_specialist",
  "uscis_forms_specialist",
  "evidence_collector"
];

export const READ_ONLY_ROLES: string[] = [
  "viewer"
];

export const CAPABILITIES: Record<string, string[]> = {
  "admin.cms.access": [
    "super_admin",
    "admin",
    "editor"
  ],
  "users.manage": [
    "super_admin",
    "admin"
  ],
  "users.delete": [
    "super_admin"
  ],
  "settings.manage": [
    "super_admin",
    "admin"
  ],
  "leads.view": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm",
    "petition_writer",
    "business_plan_specialist",
    "recommendation_letter_specialist",
    "uscis_forms_specialist",
    "evidence_collector",
    "reviewer",
    "editor",
    "viewer"
  ],
  "leads.assign": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm"
  ],
  "leads.edit": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm"
  ],
  "leads.delete": [
    "super_admin",
    "admin"
  ],
  "notes.create": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm",
    "petition_writer",
    "business_plan_specialist",
    "recommendation_letter_specialist",
    "uscis_forms_specialist",
    "evidence_collector",
    "reviewer"
  ],
  "tasks.manage": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm"
  ],
  "tasks.view_all": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm"
  ],
  "sprints.manage": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm"
  ],
  "deliveries.manage": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm",
    "petition_writer",
    "business_plan_specialist",
    "recommendation_letter_specialist",
    "uscis_forms_specialist",
    "evidence_collector",
    "reviewer"
  ],
  "blog.manage": [
    "super_admin",
    "admin",
    "editor"
  ],
  "faqs.manage": [
    "super_admin",
    "admin",
    "editor"
  ],
  "testimonials.manage": [
    "super_admin",
    "admin",
    "editor"
  ],
  "media.manage": [
    "super_admin",
    "admin",
    "editor"
  ],
  "csv.export": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm"
  ],
  "reports.view": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm"
  ],
  "cases.view": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm",
    "petition_writer",
    "business_plan_specialist",
    "recommendation_letter_specialist",
    "uscis_forms_specialist",
    "evidence_collector",
    "reviewer"
  ],
  "cases.view_all": [
    "super_admin",
    "admin",
    "operations_admin"
  ],
  "cases.create": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm"
  ],
  "cases.manage": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm"
  ],
  "cases.assign": [
    "super_admin",
    "admin",
    "operations_admin"
  ],
  "cases.archive": [
    "super_admin",
    "admin",
    "operations_admin"
  ],
  "workspace.members.manage": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm"
  ],
  "clients.view": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm"
  ],
  "clients.manage": [
    "super_admin",
    "admin",
    "operations_admin"
  ],
  "client_updates.publish": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm"
  ],
  "queries.view": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm"
  ],
  "queries.view_all": [
    "super_admin",
    "admin",
    "operations_admin"
  ],
  "queries.create": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm"
  ],
  "queries.triage": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm"
  ],
  "queries.assign": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm"
  ],
  "queries.schedule": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm"
  ],
  "queries.answer": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm"
  ],
  "queries.manage": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm"
  ],
  "queries.close": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm"
  ],
  "documents.view": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm",
    "petition_writer",
    "business_plan_specialist",
    "recommendation_letter_specialist",
    "uscis_forms_specialist",
    "evidence_collector",
    "reviewer"
  ],
  "documents.view_all": [
    "super_admin",
    "admin",
    "operations_admin"
  ],
  "documents.upload": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm"
  ],
  "documents.review": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm"
  ],
  "documents.archive": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm"
  ],
  "document_categories.manage": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm"
  ],
  "document_requests.manage": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm"
  ],
  "document_versions.view": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm",
    "petition_writer",
    "business_plan_specialist",
    "recommendation_letter_specialist",
    "uscis_forms_specialist",
    "evidence_collector",
    "reviewer"
  ],
  "channels.view": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm",
    "petition_writer",
    "business_plan_specialist",
    "recommendation_letter_specialist",
    "uscis_forms_specialist",
    "evidence_collector",
    "reviewer"
  ],
  "channels.view_all": [
    "super_admin",
    "admin",
    "operations_admin"
  ],
  "channels.create": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm"
  ],
  "channels.manage": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm"
  ],
  "channels.archive": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm"
  ],
  "channel_members.manage": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm"
  ],
  "messages.send": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm",
    "petition_writer",
    "business_plan_specialist",
    "recommendation_letter_specialist",
    "uscis_forms_specialist",
    "evidence_collector",
    "reviewer"
  ],
  "messages.edit_own": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm",
    "petition_writer",
    "business_plan_specialist",
    "recommendation_letter_specialist",
    "uscis_forms_specialist",
    "evidence_collector",
    "reviewer"
  ],
  "messages.moderate": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm"
  ],
  "messages.view_revisions": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm"
  ],
  "forms.view": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm",
    "petition_writer",
    "business_plan_specialist",
    "recommendation_letter_specialist",
    "uscis_forms_specialist",
    "evidence_collector",
    "reviewer"
  ],
  "forms.edit": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm",
    "uscis_forms_specialist"
  ],
  "forms.review": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm",
    "reviewer",
    "uscis_forms_specialist"
  ],
  "forms.lock": [
    "super_admin",
    "admin",
    "reviewer"
  ],
  "form_templates.manage": [
    "super_admin",
    "admin"
  ],
  "petitions.view": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm",
    "petition_writer",
    "business_plan_specialist",
    "recommendation_letter_specialist",
    "uscis_forms_specialist",
    "evidence_collector",
    "reviewer"
  ],
  "petitions.manage": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm"
  ],
  "petitions.edit": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm",
    "petition_writer"
  ],
  "petitions.review": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm",
    "reviewer"
  ],
  "petitions.finalize": [
    "super_admin",
    "admin",
    "reviewer"
  ],
  "filing_packets.view": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm",
    "petition_writer",
    "uscis_forms_specialist",
    "reviewer"
  ],
  "filing_packets.manage": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm",
    "uscis_forms_specialist"
  ],
  "filing_packets.review": [
    "super_admin",
    "admin",
    "operations_admin",
    "pm",
    "reviewer"
  ],
  "filing_packets.finalize": [
    "super_admin",
    "admin",
    "reviewer"
  ]
};

/**
 * Does this role hold this capability?
 *
 * Fails closed on a missing/unknown role and on an unknown capability
 * name — mirroring `can()` in permissions.js. A typo'd capability grants
 * nothing rather than everything.
 */
export function roleHasCapability(role: string | null | undefined, capability: string): boolean {
  if (!role) return false;
  const allowed = CAPABILITIES[capability];
  if (!allowed) return false;
  return allowed.includes(role);
}

/** Every capability a role holds — used to build navigation, never to authorize. */
export function capabilitiesForRole(role: string | null | undefined): string[] {
  if (!role) return [];
  return Object.keys(CAPABILITIES).filter((c) => CAPABILITIES[c].includes(role));
}

export function roleLabel(role: string | null | undefined): string {
  if (!role) return "Unknown";
  return ROLE_LABELS[role] ?? role;
}
