/**
 * Environment configuration — generated by setenv.js at build time.
 * Firebase is NOT used in the employee case-management app (ADR-016).
 */
export const environment = {
  production: false,
  apiBaseUrl: "http://localhost:4000",
};
