/**
 * setenv.js — writes environment.ts from .env variables at build/dev-server time.
 *
 * Firebase has been removed from the employee case-management app (ADR-016).
 * The employee app only communicates with the Immigration Horizons Express API.
 */
const fs = require('fs');
require('dotenv').config();

const targetPath = './projects/case-management/src/environments/environment.ts';
const envConfigFile = `/**
 * Environment configuration — generated by setenv.js at build time.
 * Firebase is NOT used in the employee case-management app (ADR-016).
 */
export const environment = {
  production: ${process.env.NODE_ENV === 'production'},
  apiBaseUrl: "${process.env.API_BASE_URL || 'http://localhost:4000'}",
};
`;

fs.writeFileSync(targetPath, envConfigFile);
console.log(`Output generated at ${targetPath}`);
