// permissions.js owns the cross-application role vocabulary (ADR-009).
/* eslint-disable @typescript-eslint/no-require-imports */
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const { ROLE_LABELS, ALL_ROLES, MANAGER_ROLES, SPECIALIST_ROLES, READ_ONLY_ROLES, CAPABILITIES } = require('../server/utils/permissions');
const contractPath = path.join(root, 'docs/architecture/employee-capability-contract.json');
const contract = JSON.parse(fs.readFileSync(contractPath, 'utf8'));
Object.assign(contract, { roles: ALL_ROLES, roleLabels: ROLE_LABELS, managerRoles: MANAGER_ROLES, specialistRoles: SPECIALIST_ROLES, readOnlyRoles: READ_ONLY_ROLES, capabilities: CAPABILITIES });
fs.writeFileSync(contractPath, JSON.stringify(contract, null, 2) + '\n');
const mirrorPath = path.join(root, 'src/lib/auth/capabilities.ts');
const previous = fs.readFileSync(mirrorPath, 'utf8');
const helpers = previous.slice(previous.indexOf('/**\n * Does this role') >= 0 ? previous.indexOf('/**\n * Does this role') : previous.indexOf('/**\r\n * Does this role'));
if (!helpers) throw new Error('Capability mirror helper marker missing.');
const declarations = [
  ['ROLE_LABELS', ROLE_LABELS, 'Record<string, string>'],
  ['ALL_ROLES', ALL_ROLES, 'string[]'],
  ['MANAGER_ROLES', MANAGER_ROLES, 'string[]'],
  ['SPECIALIST_ROLES', SPECIALIST_ROLES, 'string[]'],
  ['READ_ONLY_ROLES', READ_ONLY_ROLES, 'string[]'],
  ['CAPABILITIES', CAPABILITIES, 'Record<string, string[]>'],
].map(([name, value, type]) => `export const ${name}: ${type} = ${JSON.stringify(value, null, 2)};`).join('\n\n');
fs.writeFileSync(mirrorPath, '// Generated by scripts/generateCapabilityContract.cjs from server/utils/permissions.js.\n// Navigation uses this mirror; server policies authorize every operation.\n\n' + declarations + '\n\n' + helpers);
const { CASE_TYPES, CASE_STAGES } = require('../server/utils/caseConstants');
fs.writeFileSync(path.join(root, 'enterprise-ui/projects/case-management/src/app/core/api/case-catalog.ts'),
  '// Generated from server/utils/caseConstants.js.\n' +
  `export const CASE_TYPES = ${JSON.stringify(CASE_TYPES, null, 2)};\n` +
  `export const CASE_STAGES = ${JSON.stringify(CASE_STAGES, null, 2)};\n`);
